# Generated by Django 4.0.6 on 2022-07-31 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('travel', '0003_transport_travelrequest_event_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='event_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='event_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='journey_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='journey_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
