# Generated by Django 4.0.6 on 2022-08-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('travel', '0004_alter_travelrequest_event_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_costs', models.IntegerField(max_length=5)),
                ('transport_costs', models.IntegerField(max_length=5)),
                ('other_costs', models.IntegerField(max_length=5)),
            ],
        ),
    ]
