# Generated by Django 4.0.6 on 2022-08-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('travel', '0005_travelinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinvoice',
            name='hotel_costs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='other_costs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='transport_costs',
            field=models.IntegerField(),
        ),
    ]
