# Generated by Django 4.1 on 2022-08-10 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_travelinvoicestatus_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinvoice',
            name='status',
            field=models.ForeignKey(default='wartet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.travelinvoicestatus'),
        ),
        migrations.AlterField(
            model_name='travelinvoicestatus',
            name='status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.ForeignKey(default='wartet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.travelrequeststatus'),
        ),
        migrations.AlterField(
            model_name='travelrequeststatus',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
