# Generated by Django 4.1 on 2022-08-12 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_alter_travelrequeststatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.ForeignKey(default='wartet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.travelrequeststatus'),
        ),
    ]
