# Generated by Django 4.1 on 2022-08-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_alter_travelrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinvoice',
            name='status',
            field=models.CharField(choices=[('Wartet', 'Wartet'), ('Genehmigt', 'Genehmigt')], default='Wartet', max_length=30),
        ),
        migrations.DeleteModel(
            name='TravelInvoiceStatus',
        ),
    ]
