# Generated by Django 4.1 on 2022-08-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('travel', '0016_alter_travelinvoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/%Y%m%d-%H%M%S'),
        ),
    ]
