# Generated by Django 4.1 on 2022-08-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('travel', '0018_alter_travelrequest_event_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='%Y%m%d-%H%M%S'),
        ),
    ]
