# Generated by Django 4.1 on 2022-08-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('travel', '0019_alter_travelinvoice_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='invoiceData/c039fa01-317a-4f9b-b1b5-3dec25da583c'),
        ),
    ]
