# Generated by Django 4.1 on 2022-08-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0025_remove_travelrequest_employee_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelinvoice',
            old_name='travel_request_id',
            new_name='travel_request',
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='destination',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='event',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='invoiceData/9a3e84aa-aa36-4268-9953-3052ee255449'),
        ),
    ]
