# Generated by Django 4.1 on 2022-08-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0026_rename_travel_request_id_travelinvoice_travel_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='invoiceData/2c474a4f-de6a-4ab9-8502-1d009c72d2a9'),
        ),
    ]
