# Generated by Django 4.1 on 2022-08-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('travel', '0027_alter_travelinvoice_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelinvoice',
            options={'permissions': [('is_clerk', 'can access invoice page')]},
        ),
        migrations.AlterModelOptions(
            name='travelrequest',
            options={'permissions': [('is_supervisor', 'can access auth page')]},
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='invoiceData/5f3f8f9f-2311-477f-914b-427f9ab927d8'),
        ),
    ]
