# Generated by Django 4.1 on 2022-08-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0029_travelinvoice_event_end_travelinvoice_event_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinvoice',
            name='event_end',
            field=models.DateTimeField(default='timezone.now'),
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='event_start',
            field=models.DateTimeField(default='timezone.now'),
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='journey_end',
            field=models.DateTimeField(default='timezone.now'),
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='journey_start',
            field=models.DateTimeField(default='timezone.now'),
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='invoiceData/5aa8d047-950f-4a3e-b49a-bf7ce4eec853'),
        ),
    ]
