# Generated by Django 4.1 on 2022-08-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0033_alter_travelinvoice_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelinvoice',
            name='status',
        ),
        migrations.AddField(
            model_name='travelinvoice',
            name='ti_status',
            field=models.CharField(choices=[('In Bearbeitung', 'In Bearbeitung'), ('Auszahlung angewiesen', 'Auszahlung angewiesen')], default='In Bearbeitung', max_length=30),
        ),
        migrations.AddField(
            model_name='travelinvoice',
            name='tr_status',
            field=models.CharField(blank=True, default='In Bearbeitung', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='invoiceData/f10f85f9-837d-4d62-91f3-d45371853a2e'),
        ),
    ]
