# Generated by Django 4.1 on 2022-08-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0034_remove_travelinvoice_status_travelinvoice_ti_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='invoiceData/16738709-3c4c-4c5e-bbd5-471fc162fc74'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('In Bearbeitung', 'In Bearbeitung'), ('Genehmigt', 'Genehmigt')], default='In Bearbeitung', max_length=30),
        ),
    ]
