# Generated by Django 4.1 on 2022-08-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0039_alter_travelinvoice_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinvoice',
            name='tr_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
