# Generated by Django 4.1 on 2022-08-28 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('travel', '0040_alter_travelinvoice_tr_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelinvoice',
            name='travel_request',
        ),
    ]
