# Generated by Django 4.1 on 2022-08-12 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_alter_travelinvoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.travelrequeststatus'),
        ),
        migrations.AlterField(
            model_name='travelrequeststatus',
            name='status',
            field=models.CharField(default='wartet', max_length=30),
        ),
    ]
