# Generated by Django 4.1 on 2022-08-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_alter_travelrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('W', 'Wartet'), ('G', 'Genehmigt')], default='Wartet', max_length=30),
        ),
    ]
