# Generated by Django 4.1 on 2022-08-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0017_travelinvoice_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='event_end',
            field=models.DateTimeField(default='01.01.2022 08:00'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='event_start',
            field=models.DateTimeField(default='01.01.2022 08:00'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='journey_end',
            field=models.DateTimeField(default='01.01.2022 08:00'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='journey_start',
            field=models.DateTimeField(default='01.01.2022 08:00'),
        ),
    ]
