# Generated by Django 4.1 on 2022-08-13 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0020_alter_travelinvoice_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinvoice',
            name='travel_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.travelrequest'),
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='invoiceData/eba1403f-bdbf-4f02-aa2a-f722300d3d5e'),
        ),
    ]
