# Generated by Django 4.1 on 2022-08-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0021_travelinvoice_travel_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinvoice',
            name='destination',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='travelinvoice',
            name='event',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='invoiceData/67dab477-b924-486a-a0ab-f239b83eb2f6'),
        ),
    ]
