# Generated by Django 4.1 on 2022-08-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0022_travelinvoice_destination_travelinvoice_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='employee_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='invoiceData/4b1347a5-5dd0-44e1-a01e-79068dc02078'),
        ),
    ]
