# Generated by Django 4.1 on 2022-08-14 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0023_travelrequest_employee_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelinvoice',
            name='travel_request',
        ),
        migrations.AddField(
            model_name='travelinvoice',
            name='travel_request_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='request.travelrequest'),
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='invoiceData/4f3d5718-8698-4ec7-8d26-7993dc35260a'),
        ),
    ]
