# Generated by Django 4.1 on 2022-08-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0024_remove_travelinvoice_travel_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequest',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='travelinvoice',
            name='employee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelinvoice',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='invoiceData/cfe483e4-0d63-4f1d-9d11-07cc3628d9e8'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='employee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
