# Generated by Django 4.1 on 2022-08-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0035_alter_travelinvoice_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinvoice',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='invoiceData/e712fe68-33b1-4024-bdb7-35b4196f9e09'),
        ),
    ]
